from __future__ import annotations

DISTRICT_NAMES = {
    "01": "Boat Quay / Raffles Place / Marina",
    "02": "Chinatown / Tanjong Pagar",
    "03": "Alexandra / Commonwealth",
    "04": "Harbourfront / Telok Blangah",
    "05": "Buona Vista / West Coast / Clementi New Town",
    "06": "City Hall / Clarke Quay",
    "07": "Beach Road / Bugis / Rochor",
    "08": "Farrer Park / Serangoon Rd",
    "09": "Orchard / River Valley",
    "10": "Ardmore / Bukit Timah / Holland Rd / Tanglin",
    "11": "Watten Estate / Novena / Thomson",
    "12": "Balestier / Toa Payoh / Serangoon",
    "13": "Macpherson / Potong Pasir",
    "14": "Eunos / Geylang / Paya Lebar",
    "15": "East Coast / Marine Parade",
    "16": "Bedok / Upper East Coast",
    "17": "Changi Airport / Changi Village",
    "18": "Pasir Ris / Tampines",
    "19": "Hougang / Punggol / Sengkang",
    "20": "Ang Mo Kio / Bishan / Thomson",
    "21": "Clementi Park / Upper Bukit Timah",
    "22": "Boon Lay / Jurong / Tuas",
    "23": "Dairy Farm / Bukit Panjang / Choa Chu Kang",
    "24": "Lim Chu Kang / Tengah",
    "25": "Kranji / Woodgrove",
    "26": "Upper Thomson / Springleaf",
    "27": "Yishun / Sembawang",
    "28": "Seletar / Yio Chu Kang",
}

DISTRICT_MAP_QUERIES = {
    "01": "Marina Bay",
    "02": "Tanjong Pagar MRT",
    "03": "Commonwealth MRT",
    "04": "HarbourFront MRT",
    "05": "Clementi MRT",
    "06": "City Hall MRT",
    "07": "Bugis MRT",
    "08": "Farrer Park MRT",
    "09": "Somerset MRT",
    "10": "Botanic Gardens MRT",
    "11": "Novena MRT",
    "12": "Toa Payoh MRT",
    "13": "MacPherson MRT",
    "14": "Paya Lebar MRT",
    "15": "Marine Parade MRT",
    "16": "Bedok MRT",
    "17": "Changi Village",
    "18": "Tampines MRT",
    "19": "Sengkang MRT",
    "20": "Bishan MRT",
    "21": "Beauty World MRT",
    "22": "Jurong East MRT",
    "23": "Bukit Panjang MRT",
    "24": "Tengah",
    "25": "Kranji MRT",
    "26": "Upper Thomson MRT",
    "27": "Yishun MRT",
    "28": "Seletar Aerospace Park",
}

PLANNING_AREA_TO_DISTRICT = {
    "ANG MO KIO": "20",
    "BEDOK": "16",
    "BISHAN": "20",
    "BOON LAY": "22",
    "BUKIT BATOK": "23",
    "BUKIT MERAH": "04",
    "BUKIT PANJANG": "23",
    "BUKIT TIMAH": "21",
    "CENTRAL WATER CATCHMENT": "26",
    "CHANGI": "17",
    "CHANGI BAY": "17",
    "CHOA CHU KANG": "23",
    "CLEMENTI": "05",
    "DOWNTOWN CORE": "01",
    "GEYLANG": "14",
    "HOUGANG": "19",
    "JURONG EAST": "22",
    "JURONG WEST": "22",
    "KALLANG": "08",
    "LIM CHU KANG": "24",
    "MANDAI": "25",
    "MARINA EAST": "01",
    "MARINA SOUTH": "01",
    "MARINE PARADE": "15",
    "MUSEUM": "06",
    "NEWTON": "11",
    "NORTH-EASTERN ISLANDS": "19",
    "NOVENA": "11",
    "ORCHARD": "09",
    "OUTRAM": "02",
    "PASIR RIS": "18",
    "PAYA LEBAR": "14",
    "PIONEER": "22",
    "PUNGGOL": "19",
    "QUEENSTOWN": "03",
    "RIVER VALLEY": "09",
    "ROCHOR": "07",
    "SELETAR": "28",
    "SEMBAWANG": "27",
    "SENGKANG": "19",
    "SERANGOON": "13",
    "SIMPANG": "28",
    "SINGAPORE RIVER": "06",
    "SOUTHERN ISLANDS": "04",
    "STRAITS VIEW": "01",
    "SUNGEI KADUT": "25",
    "TAMPINES": "18",
    "TANGLIN": "10",
    "TENGAH": "24",
    "TOA PAYOH": "12",
    "TUAS": "22",
    "WESTERN ISLANDS": "22",
    "WESTERN WATER CATCHMENT": "24",
    "WOODLANDS": "25",
    "YISHUN": "27",
}

BEDROOM_BUCKETS = ["Studio / 1BR", "2BR", "3BR", "4BR+", "Unknown"]
LISTING_LAYOUT_BUCKETS = ["Studio / 1BR", "2BR", "2BR2BA", "3BR", "4BR+", "Unknown"]
PRIVATE_SEGMENTS = ["non-landed", "executive-condo", "landed"]
HDB_FLAT_TYPES = ["1-RM", "2-RM", "3-RM", "4-RM", "5-RM", "EXEC"]
HDB_TOWNS = [
    "ANG MO KIO",
    "BEDOK",
    "BISHAN",
    "BUKIT BATOK",
    "BUKIT MERAH",
    "BUKIT PANJANG",
    "BUKIT TIMAH",
    "CENTRAL AREA",
    "CHOA CHU KANG",
    "CLEMENTI",
    "GEYLANG",
    "HOUGANG",
    "JURONG EAST",
    "JURONG WEST",
    "KALLANG/WHAMPOA",
    "MARINE PARADE",
    "PASIR RIS",
    "PUNGGOL",
    "QUEENSTOWN",
    "SEMBAWANG",
    "SENGKANG",
    "SERANGOON",
    "TAMPINES",
    "TOA PAYOH",
    "WOODLANDS",
    "YISHUN",
]
